# Generated by Django 3.2.18 on 2023-03-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='age',
        ),
        migrations.AddField(
            model_name='form',
            name='message',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
